// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gxozvoquyehevodijocr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd4b3p2b3F1eWVoZXZvZGlqb2NyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5OTE1NDMsImV4cCI6MjA3MDU2NzU0M30.3nAoDJCIa95xZFwKG8jS2Y4q92QHabyVyUXuyYztha8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});